services:
  - type: web
    name: segundo-cerebro-bot
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL
        value: "openai/gpt-oss-20b"
      - key: RENDER_EXTERNAL_URL
        sync: false
      - key: TURSO_URL
        sync: false
      - key: TURSO_TOKEN
        sync: false
